export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const LOAD_CURRENT_LOCATION = "LOAD_CURRENT_LOCATION";
export const LOAD_CURRENT_WEATHER = "LOAD_CURRENT_WEATHER";
export const LOAD_CURRENT_FORECAST = "LOAD_CURRENT_FORECAST";
export const SHOW_WEATHER = "SHOW_WEATHER";
